# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kwatanab <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/07 14:55:53 by kwatanab          #+#    #+#              #
#    Updated: 2018/11/07 14:55:57 by kwatanab         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: main

main:
	gcc -c -Wall -Werror -Wextra ft_display_file.c
	gcc -o ft_display_file ft_display_file.o

clean:
	/bin/rm -rf *.o

fclean: clean
	/bin/rm -rf ft_display_file
